### ISSUE TITLE
How to get a clear picture for a big tree.

### ISSUE THREAD

**Issue by zhulishe** [ChuckWoodraska/EurekaTrees#1]
I have a tree with too many nodes, making nodes overlapping. How can I get a clear picture?Ths
![pic](https://cloud.githubusercontent.com/assets/14036049/25071706/dd3ed4ea-22f0-11e7-8698-cbff54136ae0.PNG)

**Comment by ChuckWoodraska** [comment]
The quick fix for this is going to be to go into templates/tree_template.jinja2 and at around line 59 there is this code:
```javascript
 // ************** Generate the tree diagram	 *****************

    var margin = {top: 40, right: 40, bottom: 20, left: 40},
            width = 3600 - margin.right - margin.left,
            height = 3000 - margin.top - margin.bottom;
}
```

You can change the width and height constants until everything fits. For instance:

```javascript
 // ************** Generate the tree diagram	 *****************

    var margin = {top: 40, right: 40, bottom: 20, left: 40},
            width = 12000 - margin.right - margin.left,
            height = 10000 - margin.top - margin.bottom;
}
```

I'll try to find a way to do this programmatically so no one has to fiddle with this.

**Comment by ChuckWoodraska** [comment]
This should be fixed now. I calculate the max depth and breadth of the tree to set the canvas size.
