### ISSUE TITLE
Buggy Visualization

### ISSUE THREAD

**Issue by Guiraiol** [ChuckWoodraska/EurekaTrees#2]
Hi, I'm trying to use this project, but when it scales horizontally this happens:
![image](https://user-images.githubusercontent.com/22764886/29512830-ae675e18-8663-11e7-98ca-27df4ea97556.png)
This happen in every browser that I tested (chrome, firefox, edge)
Are there some configuration to resolve this?
Thanks in advance

**Comment by ChuckWoodraska** [comment]
The quick fix for this is going to be to go into templates/tree_template.jinja2 and at around line 59 there is this code:
```javascript
 // ************** Generate the tree diagram	 *****************

    var margin = {top: 40, right: 40, bottom: 20, left: 40},
            width = {{ max_breadth }} - margin.right - margin.left,
            height = {{ max_depth }} - margin.top - margin.bottom;
```

You can change the width and height constants until everything fits. For instance:

```javascript
 // ************** Generate the tree diagram	 *****************

    var margin = {top: 40, right: 40, bottom: 20, left: 40},
            width = 12000 - margin.right - margin.left,
            height = 10000 - margin.top - margin.bottom;
}
```

I'll try to find a way to do this programmatically so no one has to fiddle with this. It also looks like something else is going on with the nodes reaching points where they are both outputting 0 as the prediction. Is there any way you could send me this tree?

**Comment by ChuckWoodraska** [comment]
I think I fixed the issue for your specific problem. I now stack the labels and splay out the branches further so that close branches shouldn't overlap anymore. This does end up taking up more screen real estate so more scrolling is necessary but some of this can be alleviated by zooming out. Please let me know if this fixes the issue for you.

**Comment by Guiraiol** [comment]
I forgot to let you know that the first quick fix worked . I'll test new fix as soon as possible. 
Thank you so much for the attention

**Comment by ChuckWoodraska** [comment]
Closing as I think this is fixed.
